import { ArrowRight, FlaskConical, GitCompareArrows, ListChecks } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ErrorState, LoadingState, Metric, MetricStrip, PageHeader, Panel, PanelBody, PanelHeader } from '@/shared/ui';
import { formatDateTime } from '@/shared/lib/format';
import { useRuns, useTasks } from '../hooks/queries';
import { TaskStatusBadge } from '../components/TaskStatusBadge';

export function BacktestsHomePage() { const tasks = useTasks(); const runs = useRuns(); if (tasks.isLoading || runs.isLoading) return <LoadingState label="正在读取回测工作区…" />; if (tasks.isError) return <ErrorState error={tasks.error} onRetry={() => void tasks.refetch()} />; if (runs.isError) return <ErrorState error={runs.error} onRetry={() => void runs.refetch()} />; const recentTasks = tasks.data?.slice(0, 5) ?? []; const recentRuns = runs.data?.slice(0, 5) ?? []; return <div className="stack"><PageHeader eyebrow="回测实验室" title="从假设到可复现结果" description="创建真实任务、跟踪运行、分析标准结果包，并在统一口径下比较实验。" actions={<Link className="button button--primary button--md" to="/backtests/new"><FlaskConical size={15} />新建回测</Link>} />
  <MetricStrip><Metric label="任务总数" value={tasks.data?.length ?? 0} meta="持久化任务" /><Metric label="标准结果" value={runs.data?.length ?? 0} meta="可打开的 run" /><Metric label="运行中" value={tasks.data?.filter((t) => ['queued','running','pending'].includes(t.status)).length ?? 0} tone="warning" /><Metric label="失败" value={tasks.data?.filter((t) => t.status === 'failed').length ?? 0} tone="down" /></MetricStrip>
  <div className="workflow-rail"><Link to="/strategies"><span>01</span><strong>选择策略</strong><small>查看参数与数据依赖</small></Link><Link to="/backtests/new"><span>02</span><strong>创建任务</strong><small>定义 Universe、日期和成本</small></Link><Link to="/backtests/tasks"><span>03</span><strong>跟踪运行</strong><small>状态、错误与 run 关联</small></Link><Link to="/backtests/runs"><span>04</span><strong>分析结果</strong><small>指标、图表、交易和诊断</small></Link><Link to="/backtests/compare"><span>05</span><strong>比较实验</strong><small>统一指标与配置差异</small></Link></div>
  <div className="grid grid--2"><Panel><PanelHeader title="最近任务" actions={<Link className="text-link" to="/backtests/tasks">全部任务 <ArrowRight size={13} /></Link>} /><PanelBody className="panel__body--flush">{recentTasks.length ? <table className="data-table"><tbody>{recentTasks.map((task) => <tr key={task.task_id}><td><Link className="table-link" to={`/backtests/tasks/${task.task_id}`}>{task.name}</Link><div className="table-subtitle">{formatDateTime(task.created_at)}</div></td><td><TaskStatusBadge status={task.status} /></td></tr>)}</tbody></table> : <div className="state-block">暂无任务</div>}</PanelBody></Panel>
  <Panel><PanelHeader title="最近结果" actions={<Link className="text-link" to="/backtests/runs">结果库 <ArrowRight size={13} /></Link>} /><PanelBody className="panel__body--flush">{recentRuns.length ? <table className="data-table"><tbody>{recentRuns.map((run) => <tr key={run.run_id}><td><Link className="table-link" to={`/backtests/runs/${run.run_id}`}>{run.name}</Link><div className="table-subtitle">{run.strategy_name} · {run.start_date}—{run.end_date}</div></td><td><Link className="icon-link" to={`/backtests/compare?run=${run.run_id}`} title="加入比较"><GitCompareArrows size={14} /></Link></td></tr>)}</tbody></table> : <div className="state-block">暂无标准结果</div>}</PanelBody></Panel></div>
  <div className="quick-links"><Link to="/backtests/tasks"><ListChecks size={15} />任务队列</Link><Link to="/backtests/compare"><GitCompareArrows size={15} />结果比较</Link></div></div>; }
