import { GitCompareArrows } from 'lucide-react';
import { Link, NavLink, useParams, useSearchParams } from 'react-router-dom';
import { backtestsApi } from '../api/backtestsApi';
import { useRun, useRunArtifact } from '../hooks/queries';
import { ErrorState, LoadingState, PageHeader, Panel, PanelBody, PanelHeader, EmptyState, StatusBadge } from '@/shared/ui';
import { formatDateTime, formatMoney, formatNumber, formatPercent } from '@/shared/lib/format';
import { EquityChart } from '@/shared/charts/EquityChart';
import { RunMetrics } from '../components/RunMetrics';

const tabs = [{ id: 'overview', label: '概览' }, { id: 'trades', label: '交易' }, { id: 'diagnostics', label: '诊断' }, { id: 'config', label: '配置与复现' }];
export function RunDetailPage() { const { runId = '' } = useParams(); const [search] = useSearchParams(); const tab = search.get('tab') ?? 'overview'; const run = useRun(runId); const summary = useRunArtifact(runId, 'summary', () => backtestsApi.getSummary(runId)); const equity = useRunArtifact(runId, 'equity', () => backtestsApi.getEquity(runId));
 if (run.isLoading) return <LoadingState label="正在打开标准结果包…" />; if (run.isError) return <ErrorState error={run.error} onRetry={() => void run.refetch()} />; if (!run.data) return null;
 return <div className="stack"><PageHeader eyebrow="标准回测结果" title={run.data.name} description={`${run.data.strategy_name} · ${run.data.universe}`} meta={<span className="inline"><StatusBadge tone="success">{run.data.status}</StatusBadge><code>{runId}</code><span>{run.data.start_date}—{run.data.end_date}</span><span>生成 {formatDateTime(run.data.created_at)}</span></span>} actions={<Link className="button button--secondary button--md" to={`/backtests/compare?run=${encodeURIComponent(runId)}`}><GitCompareArrows size={15} />加入比较</Link>} />
 <nav className="tabs" aria-label="结果内容">{tabs.map((item) => <NavLink key={item.id} to={`?tab=${item.id}`} className={tab === item.id ? 'active' : ''}>{item.label}</NavLink>)}</nav>
 {tab === 'overview' ? <OverviewTab runId={runId} summary={summary} equity={equity} /> : null}{tab === 'trades' ? <TradesTab runId={runId} /> : null}{tab === 'diagnostics' ? <DiagnosticsTab runId={runId} /> : null}{tab === 'config' ? <ConfigTab runId={runId} /> : null}
 </div>; }

function OverviewTab({ runId, summary, equity }: { runId: string; summary: ReturnType<typeof useRunArtifact<Awaited<ReturnType<typeof backtestsApi.getSummary>>>>; equity: ReturnType<typeof useRunArtifact<Awaited<ReturnType<typeof backtestsApi.getEquity>>>> }) {
 const costs = useRunArtifact(runId, 'costs', () => backtestsApi.getCosts(runId));
 if (summary.isLoading || equity.isLoading) return <LoadingState label="正在读取指标与净值…" />; if (summary.isError) return <ErrorState error={summary.error} onRetry={() => void summary.refetch()} />; if (equity.isError) return <ErrorState error={equity.error} onRetry={() => void equity.refetch()} />; if (!summary.data) return null;
 return <div className="stack"><RunMetrics summary={summary.data} /><div className="grid grid--main-aside"><Panel><PanelHeader title="净值与回撤" meta={`${equity.data?.length ?? 0} 个交易日 · 绿色净值 / 红色回撤`} /><PanelBody>{equity.data?.length ? <EquityChart points={equity.data} /> : <EmptyState title="结果包没有净值序列" />}</PanelBody></Panel><Panel><PanelHeader title="绩效明细" /><PanelBody><dl className="definition-list"><dt>Sortino</dt><dd>{formatNumber(summary.data.sortino)}</dd><dt>Calmar</dt><dd>{formatNumber(summary.data.calmar)}</dd><dt>盈亏比</dt><dd>{formatNumber(summary.data.profit_loss_ratio)}</dd><dt>平均持有</dt><dd>{formatNumber(summary.data.avg_holding_days)} 天</dd><dt>最大单笔盈利</dt><dd>{formatPercent(summary.data.max_trade_profit_pct)}</dd><dt>最大单笔亏损</dt><dd>{formatPercent(summary.data.max_trade_loss_pct)}</dd><dt>最终权益</dt><dd>{formatMoney(summary.data.final_equity)}</dd></dl></PanelBody></Panel></div>
 <Panel><PanelHeader title="交易成本" meta={costs.data ? '后端结果包成本归因' : '结果包未提供成本明细'} /><PanelBody>{costs.isLoading ? <LoadingState /> : costs.isError ? <ErrorState error={costs.error} /> : costs.data ? <dl className="definition-list"><dt>佣金</dt><dd>{formatMoney(costs.data.commission)}</dd><dt>印花税</dt><dd>{formatMoney(costs.data.stamp_tax)}</dd><dt>滑点成本</dt><dd>{formatMoney(costs.data.slippage_cost)}</dd><dt>总成本</dt><dd>{formatMoney(costs.data.total_cost)}</dd><dt>换手</dt><dd>{formatNumber(costs.data.turnover)}</dd></dl> : <EmptyState title="没有成本归因" />}</PanelBody></Panel></div>;
}
function TradesTab({ runId }: { runId: string }) { const trades = useRunArtifact(runId, 'trades', () => backtestsApi.getTrades(runId)); const skipped = useRunArtifact(runId, 'skipped', () => backtestsApi.getSkipped(runId)); if (trades.isLoading) return <LoadingState label="正在读取交易记录…" />; if (trades.isError) return <ErrorState error={trades.error} onRetry={() => void trades.refetch()} />; return <div className="stack"><Panel><PanelHeader title="成交交易" meta={`${trades.data?.length ?? 0} 笔`} /><PanelBody className="panel__body--flush">{!trades.data?.length ? <EmptyState title="本次回测没有成交交易" /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>证券</th><th>信号/入场</th><th>出场</th><th className="numeric">入场价</th><th className="numeric">出场价</th><th className="numeric">收益</th><th className="numeric">MAE / MFE</th><th>退出原因</th></tr></thead><tbody>{trades.data.map((t) => <tr key={t.trade_id}><td>{t.asset_id}<div className="table-subtitle">{t.status}</div></td><td>{t.signal_date}<br />{t.entry_date}</td><td>{t.exit_date ?? '持仓中'}</td><td className="numeric">{formatNumber(t.entry_price, 3)}</td><td className="numeric">{formatNumber(t.exit_price, 3)}</td><td className={`numeric ${t.return_pct && t.return_pct > 0 ? 'up' : 'down'}`}>{formatPercent(t.return_pct)}</td><td className="numeric">{formatPercent(t.mae_pct)} / {formatPercent(t.mfe_pct)}</td><td>{t.exit_reason ?? '—'}</td></tr>)}</tbody></table></div>}</PanelBody></Panel>
 <Panel><PanelHeader title="跳过信号" meta={`${skipped.data?.length ?? 0} 条`} /><PanelBody className="panel__body--flush">{skipped.isLoading ? <LoadingState /> : skipped.isError ? <ErrorState error={skipped.error} /> : !skipped.data?.length ? <EmptyState title="没有跳过信号" /> : <table className="data-table"><thead><tr><th>证券</th><th>信号日</th><th>原因</th><th>详情</th></tr></thead><tbody>{skipped.data.map((s, index) => <tr key={`${s.asset_id}:${s.signal_date}:${index}`}><td>{s.asset_id ?? '—'}</td><td>{s.signal_date ?? '—'}</td><td>{s.reason}</td><td>{s.detail ?? '—'}</td></tr>)}</tbody></table>}</PanelBody></Panel></div>; }
function DiagnosticsTab({ runId }: { runId: string }) { const d = useRunArtifact(runId, 'diagnostics', () => backtestsApi.getDiagnostics(runId)); if (d.isLoading) return <LoadingState />; if (d.isError) return <ErrorState error={d.error} onRetry={() => void d.refetch()} />; if (!d.data) return <EmptyState title="结果包没有诊断文件" />; const flags = [['订单',d.data.has_orders,d.data.order_count],['成交',d.data.has_fills,d.data.fill_count],['快照',d.data.has_snapshots,d.data.snapshot_count],['日收益',d.data.has_daily_returns,''],['滚动绩效',d.data.has_rolling_performance,''],['基准',d.data.has_benchmark,''],['暴露',d.data.has_exposures,'']]; return <div className="grid grid--main-aside"><Panel><PanelHeader title="结果包完整性" meta={`package ${d.data.result_package_version ?? '未知版本'}`} /><PanelBody><div className="diagnostic-grid">{flags.map(([label,ok,count]) => <div key={String(label)}><StatusBadge tone={ok ? 'success' : 'neutral'}>{ok ? '存在' : '缺失'}</StatusBadge><strong>{label}</strong><span>{String(count)}</span></div>)}</div></PanelBody></Panel><Panel><PanelHeader title="诊断摘要" /><PanelBody><dl className="definition-list"><dt>交易</dt><dd>{d.data.trade_count}</dd><dt>跳过</dt><dd>{d.data.skipped_count}</dd><dt>Full loss</dt><dd>{d.data.full_loss ? '是' : '否'}</dd><dt>Artifacts</dt><dd>{d.data.artifact_set.join('、') || '—'}</dd></dl>{d.data.benchmark_diagnostics.length ? <ul>{d.data.benchmark_diagnostics.map((x) => <li key={x}>{x}</li>)}</ul> : null}</PanelBody></Panel></div>; }
function ConfigTab({ runId }: { runId: string }) { const config = useRunArtifact(runId, 'config', () => backtestsApi.getConfig(runId)); const repro = useRunArtifact(runId, 'reproducibility', () => backtestsApi.getArtifact(runId, 'reproducibility')); if (config.isLoading) return <LoadingState />; if (config.isError) return <ErrorState error={config.error} />; return <div className="grid grid--2"><Panel><PanelHeader title="运行配置快照" /><PanelBody><pre className="code-block">{JSON.stringify(config.data?.config ?? {}, null, 2)}</pre></PanelBody></Panel><Panel><PanelHeader title="可复现性清单" meta="数据指纹、Universe 和 replay 能力由后端记录" /><PanelBody>{repro.isLoading ? <LoadingState /> : repro.isError ? <ErrorState error={repro.error} /> : <pre className="code-block">{JSON.stringify(repro.data ?? {}, null, 2)}</pre>}</PanelBody></Panel></div>; }
