import { GitCompareArrows } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { EmptyState, ErrorState, LoadingState, PageHeader, Panel, PanelBody, PanelHeader } from '@/shared/ui';
import { formatDateTime } from '@/shared/lib/format';
import { useRuns } from '../hooks/queries';
import { backtestHref, parseBacktestSource } from '../lib/source';
import { TaskStatusBadge } from '../components/TaskStatusBadge';

const sources = [{ value: 'product', label: '生产回测' }, { value: 'research', label: '研究区' }] as const;

export function RunsPage() { const [search] = useSearchParams(); const source = parseBacktestSource(search.toString()); const isResearch = source === 'research'; const query = useRuns(source); return <div className="stack"><PageHeader eyebrow="回测实验室" title="标准结果库" description={isResearch ? '研究区（backtest-research）产出的 run，产物契约与生产一致；只读展示，不含任务与策略能力。' : '每个 run 对应后端写入的标准结果包；指标、交易、诊断和配置保持同一身份。'} actions={<Link className="button button--secondary button--md" to={backtestHref('/backtests/compare', source)}><GitCompareArrows size={15} />比较结果</Link>} />
  <nav className="tabs" aria-label="数据源">{sources.map((item) => <Link key={item.value} to={backtestHref('/backtests/runs', item.value)} className={source === item.value ? 'active' : ''}>{item.label}</Link>)}</nav>
  <Panel><PanelHeader title="全部结果" meta={query.data ? `${query.data.length} 个 run` : '读取中'} /><PanelBody className="panel__body--flush">{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState error={query.error} onRetry={() => void query.refetch()} /> : !query.data?.length ? <EmptyState title={isResearch ? '研究区还没有结果' : '还没有标准结果'} description={isResearch ? '在研究区运行 scripts/run_backtest.py 产出 run 后，结果会在这里出现。' : '创建并成功执行回测任务后，结果会在这里出现。'} /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>实验</th><th>策略</th><th>Universe</th><th>区间</th><th>状态</th><th>生成时间</th><th>比较</th></tr></thead><tbody>{query.data.map((run) => <tr key={run.run_id}><td><Link className="table-link" to={backtestHref(`/backtests/runs/${run.run_id}`, source)}>{run.name}</Link><div className="table-subtitle">{run.run_id}</div></td><td>{run.strategy_name}</td><td>{run.universe}</td><td>{run.start_date}<br />{run.end_date}</td><td><TaskStatusBadge status={run.status} /></td><td>{formatDateTime(run.created_at)}</td><td><Link className="icon-link" to={backtestHref('/backtests/compare', source, `run=${encodeURIComponent(run.run_id)}`)}><GitCompareArrows size={14} /></Link></td></tr>)}</tbody></table></div>}</PanelBody></Panel></div>; }