import { ArrowRight, RotateCw } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { Button, ErrorState, LoadingState, PageHeader, Panel, PanelBody, PanelHeader, StatusBadge } from '@/shared/ui';
import { formatDateTime, formatMoney, formatPercent } from '@/shared/lib/format';
import { useTask } from '../hooks/queries';
import { TaskStatusBadge } from '../components/TaskStatusBadge';
import { isTaskActive } from '../lib/status';

export function TaskDetailPage() { const { taskId = '' } = useParams(); const query = useTask(taskId); if (query.isLoading) return <LoadingState label="正在读取任务状态…" />; if (query.isError) return <ErrorState error={query.error} onRetry={() => void query.refetch()} />; const task = query.data; if (!task) return null; return <div className="stack"><PageHeader eyebrow="回测任务" title={task.name} description={`${task.strategy_code} · ${task.start_date} 至 ${task.end_date}`} meta={<span className="inline"><TaskStatusBadge status={task.status} />{task.is_mock ? <StatusBadge tone="danger">Mock</StatusBadge> : <StatusBadge tone="success">真实执行</StatusBadge>}<code>{task.task_id}</code></span>} actions={<span className="inline"><Button onClick={() => void query.refetch()}><RotateCw size={14} />刷新</Button>{task.run_id ? <Link className="button button--primary button--md" to={`/backtests/runs/${task.run_id}`}>打开标准结果 <ArrowRight size={14} /></Link> : null}</span>} />
  {isTaskActive(task.status) ? <div className="activity-banner"><span className="spinner" /><div><strong>任务正在执行</strong><p>页面每 2 秒刷新一次状态；完成后将出现标准结果入口。</p></div></div> : null}{task.error_message ? <div className="error-banner"><strong>后端执行失败</strong><pre>{task.error_message}</pre></div> : null}
  <div className="grid grid--main-aside"><Panel><PanelHeader title="任务配置" meta={`创建 ${formatDateTime(task.created_at)} · 更新 ${formatDateTime(task.updated_at)}`} /><PanelBody><dl className="definition-list"><dt>策略</dt><dd>{task.strategy_code} · {task.strategy_version}</dd><dt>Universe 模式</dt><dd>{task.universe_mode}</dd><dt>证券范围</dt><dd>{task.tickers.join('、') || task.index_code || task.universe_preset || '—'}</dd><dt>基准</dt><dd>{task.benchmark_id ?? '—'}</dd><dt>执行时点</dt><dd>{task.execution.entry_timing}</dd><dt>策略参数</dt><dd><code>{JSON.stringify(task.strategy_params)}</code></dd></dl></PanelBody></Panel>
  <div className="stack"><Panel><PanelHeader title="组合约束" /><PanelBody><dl className="definition-list"><dt>初始资金</dt><dd>{formatMoney(task.position.initial_cash)}</dd><dt>最大持仓</dt><dd>{task.position.max_positions}</dd><dt>单票权重</dt><dd>{formatPercent(task.position.max_weight_per_symbol * 100)}</dd></dl></PanelBody></Panel><Panel><PanelHeader title="成本假设" /><PanelBody><dl className="definition-list"><dt>佣金率</dt><dd>{formatPercent(task.cost.commission_rate * 100, 4)}</dd><dt>印花税</dt><dd>{formatPercent(task.cost.stamp_tax_rate * 100, 4)}</dd><dt>滑点</dt><dd>{task.cost.slippage_bps} bps</dd></dl></PanelBody></Panel></div></div>
  <Panel><PanelHeader title="请求快照" meta="用于审计前端提交与后端持久化结果" /><PanelBody><pre className="code-block">{JSON.stringify(task.request_snapshot, null, 2)}</pre></PanelBody></Panel></div>; }
